.travis.yml
Rakefile

The purpose of this pull request is to use docker to launch Elasticsearch, instead of downloading and extracting the tarball.
Note: It is expected that the integration tests will fail, as the work in [this pull request](https://github.com/elastic/elasticsearch-rails/pull/802) is necessary for the tests to pass on ES 6.x.
The tests against Rails 3.0 are also expected to fail. A separate pull request will be made to update the matrix.

[CI] Use docker to launch Elasticsearch in rake task

---

.travis.yml
elasticsearch-model/Rakefile
elasticsearch-model/test/unit/multimodel_test.rb

=> for each in Ruby version: 2.5.x, 2.4.x, 2.3.x, 2.2.x, JRuby-9.2.x
-> UNIT w/ Rails 3
-> UNIT w/ Rails 4
-> UNIT w/ Rails 5
=> Ruby 2.5.x (latest stable version)
-> INTEGRATION w Rails 5 & ES 5.x.y (latest stable version)

[CI] Update Travis matrix for 5.x branch

---

elasticsearch-model/test/integration/mongoid_basic_test.rb
elasticsearch-model/test/integration/multiple_models_test.rb
elasticsearch-model/test/test_helper.rb

* Update the name of helper module in `test_helper.rb` to `MongoDB` to avoid name clash with MongoDB Ruby driver (`Mongo`)
* Update instantiation of MongoDB Ruby driver client

[CI] Update references to MongoDB Ruby driver

---

elasticsearch-persistence/lib/elasticsearch/persistence/repository/find.rb
elasticsearch-persistence/lib/elasticsearch/persistence/repository/naming.rb
elasticsearch-persistence/lib/elasticsearch/persistence/repository/search.rb
elasticsearch-persistence/lib/elasticsearch/persistence/repository/serialize.rb
elasticsearch-persistence/lib/elasticsearch/persistence/repository/store.rb
elasticsearch-persistence/test/integration/repository/custom_class_test.rb
elasticsearch-persistence/test/integration/repository/default_class_test.rb
elasticsearch-persistence/test/integration/repository/virtus_model_test.rb
elasticsearch-persistence/test/unit/repository_find_test.rb
elasticsearch-persistence/test/unit/repository_naming_test.rb
elasticsearch-persistence/test/unit/repository_search_test.rb
elasticsearch-persistence/test/unit/repository_serialize_test.rb
elasticsearch-persistence/test/unit/repository_store_test.rb

See [this documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_schedule_for_removal_of_mapping_types).
These changes will require users to define a `document_type` and `klass` on repository objects if they want to maintain previous behavior.
The changes create a path for users to upgrade smoothly to ES 6 and to future versions of ES. Ultimately, document_type will be removed in 7.0, as there won't be the ability to define a mapping type.

[STORE] Make default doc type '_doc' in preparation for deprecation of mapping types

---

elasticsearch-model/README.md

Hey guys
I just added readme condition for such case:
Instance of article exists, persisted, and published so successfully indexed. Then, if you make it unpublished, according to current example it will not be indexed, because 
```ruby
self.published? == true
```
I've added condition to delete document if it's non-published, and update if published. In case document was published (created),  then deleted (on update hook), and then published again, `__elasticsearch__.update_document` will create a new document.
Second point is exception handling - when gem trying to delete non-existing document, it throws `Elasticsearch::Transport::Transport::Errors::NotFound`. I've just added `rescue` for it.
Thank you.

Added condition for :update after commit & rescue if record NotFound

---

elasticsearch-model/lib/elasticsearch/model/indexing.rb
elasticsearch-model/test/unit/indexing_test.rb

@dim0627 pointed out in #743 that calling `update_attributes({})` on an ActiveRecord model instance triggers the `before_save` callback, even when there are no attributes to update. This results in an unnecessary empty update request to elasticsearch.
Using ActiveSupport's `presence`, it will act the same for both `nil` and `{}`, which are both ways Rails can express that there are no changes to save.
Closes #743

[MODEL] Avoid making an update when no attributes are changed

---

elasticsearch-model/lib/elasticsearch/model/adapters/mongoid.rb
elasticsearch-model/test/integration/mongoid_basic_test.rb
elasticsearch-model/test/unit/adapter_mongoid_test.rb

The elasticsearch model readme said It's possible to import only records from scope or query and preprocess batch data but it's not implemented

[MODEL] Support :scope, :query and :preprocess importing options for Mongoid

---

elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb
elasticsearch-model/test/integration/active_record_basic_test.rb

This is addressing an issue in #546 
The monkey patching regarding sort order was not removed when calling `order` on ActiveRecord versions >= 5.
The code introduced in https://github.com/elastic/elasticsearch-rails/pull/618 did not change the `order` method, this patch fixes it.
I have added a test that fails without my new code. The problem with testing the order with `.first` is that it applies the sql `LIMIT 1`, which would return a collection of 1 item from the database. But we want to test the order of the collection returned. Therefore, I added a test for the first item of the collection with `[0]` which doesn't limit the results returned from the db.

[MODEL] Fix sort order on ActiveRecord >= 5

---

elasticsearch-model/lib/elasticsearch/model/response.rb
elasticsearch-model/lib/elasticsearch/model/response/base.rb
elasticsearch-model/test/unit/response_results_test.rb
elasticsearch-persistence/lib/elasticsearch/persistence/repository/response/results.rb
elasticsearch-persistence/spec/repository/response/results_spec.rb

This pull request intends to address the performance issues caused by request responses being wrapped in a `HashWrapper`.
The associated issue and pull request are:
- Issue: https://github.com/elastic/elasticsearch-rails/issues/161
- Pull Request https://github.com/elastic/elasticsearch-rails/pull/755
The changes in this pull request, provide a `#raw_response` method on the response, if users want to avoid creating a HashWrapper for the response results. It also only creates the HashWrapper when the response is accessed, not upon instantiation of the `Repository::Response::Results` object.

[STORE] [MODEL] Address performance of HashWrapper in Response objects

---

elasticsearch-model/lib/elasticsearch/model/importing.rb
elasticsearch-model/test/unit/importing_test.rb

Fixes #506
When specifying the index option and refresh option on import, the imported index is not refreshed because the specified index name is not used for refreshing.

[MODEL] Fix import method to pass index name on refresh

---

elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb
elasticsearch-model/test/unit/adapter_active_record_test.rb

Closes #719 and also fixes existing test on preprocess which had no effect.

[MODEL] Fix import when preprocess returns empty collection

---

elasticsearch-rails/lib/rails/templates/seeds.rb

The expert template was using the outdated YAML.load_documents, which is no longer present in the newer versions of Ruby.

[RAILS] Fix seeds file to stop using outdated YAML method

---

elasticsearch-model/lib/elasticsearch/model/response.rb

Alternative to https://github.com/elastic/elasticsearch-rails/pull/847

[MODEL] Avoid executing search twice; Reuse response in Response#raw_response

---

elasticsearch-persistence/lib/elasticsearch/persistence/repository.rb
elasticsearch-persistence/spec/repository_spec.rb

https://github.com/elastic/elasticsearch-rails/issues/852

[STORE] Ensure that arguments are passed to super

---

elasticsearch-rails/lib/rails/templates/03-expert.rb

The variable `tracer` is only defined in Rails development env, so we only can set them in that env.

[RAILS] Fixed 03-expert.rb set tracer only in dev env

---

elasticsearch-model/lib/elasticsearch/model/indexing.rb
elasticsearch-model/spec/elasticsearch/model/indexing_spec.rb

Currently if a model has an attribute changed, but that attribute is not part of the elasticsearch template, an empty update will be made to elasticsearch.  This change only follows through on the update if there is content in the distilled attributes hash.

Only execute update if document attributes is not empty

---

.travis.yml
elasticsearch-model/lib/elasticsearch/model/indexing.rb
elasticsearch-model/spec/elasticsearch/model/indexing_spec.rb

Ref: https://github.com/elastic/elasticsearch-rails/issues/571

[MODEL] Use logger to log index not found message

---

elasticsearch-model/README.md

I found an inconsistency method name, inside README of elasticsearch-model's Asynchronous Callbacks section.
You wrote Article Model file as below.
```ruby
class Article
include Elasticsearch::Model
after_save    { Indexer.perform_async(:index,  self.id) }
after_destroy { Indexer.perform_async(:delete, self.id) }
end
```
But, you wrote example implementation of the Indexer worker class as below.
```ruby
class Indexer
include Sidekiq::Worker
sidekiq_options queue: 'elasticsearch', retry: false
［...]
def perform(operation, record_id)
［...]
end
end
```
I think we should fix Indexer worker class's method name from `perform` to `perform_async`.

Fix README elasticsearch-model

---

elasticsearch-rails/lib/rails/templates/01-basic.rb

There is a `not defined in config/webpacker.yml` error when running the command from the readme:
`rails new searchapp --skip --skip-bundle --template https://raw.github.com/vysogot/elasticsearch-rails/master/elasticsearch-rails/lib/rails/templates/01-basic.rb`
Here's the partial output from before the change:
```
run    rails server --port=3001 from "."
=> Booting Puma
=> Rails 6.0.0.beta3 application starting in development 
=> Run `rails server --help` for more startup options
RAILS_ENV=development environment is not defined in config/webpacker.yml, falling back to production environment
Exiting
Traceback (most recent call last):
68: from bin/rails:4:in `<main>'
67: from /Users/jgodawa/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.beta3/lib/active_support/dependencie …
```

Fix: Install webpacker before running the server

---

elasticsearch-model/lib/elasticsearch/model/naming.rb
elasticsearch-model/spec/elasticsearch/model/naming_inheritance_spec.rb

Closes elastic#717 & Closes elastic#585

[Model] Fix naming with inheritance when using Proxy

---

elasticsearch-model/lib/elasticsearch/model/indexing.rb
elasticsearch-model/spec/elasticsearch/model/indexing_spec.rb

This reduces the changes eventually needed for Elasticsearch v8.0.

[MODEL] Only add the document_type to the request if it's defined

---

elasticsearch-model/lib/elasticsearch/model/response/records.rb
elasticsearch-persistence/examples/notes/application.rb

`initialize` method returned value is not used usually. Because the method is called by `Class.new`.
So the `self` are not necessary.
note
===
If it is called explicitly, the caller can use the returned value. But it is a super rare case.
```ruby
class C
def initialize
1
end
end
c = C.new
p c.__send__ :initialize # => 1
```

Remove unnecessary `self` as a return value of `initialize` method

---

elasticsearch-model/README.md
elasticsearch-model/lib/elasticsearch/model.rb
elasticsearch-model/lib/elasticsearch/model/naming.rb
elasticsearch-model/spec/elasticsearch/model/module_spec.rb
elasticsearch-model/spec/elasticsearch/model/naming_inheritance_spec.rb

* [MODEL] Add warning and documentation about STI support being deprecated
* [MODEL] Minor change to STI deprecation warning
* [MODEL] Freeze string constant depreaction warning

[MODEL] Add warning and documentation about STI support being deprecated

---

Rakefile
elasticsearch-model/gemfiles/6.0.gemfile
elasticsearch-model/spec/spec_helper.rb
elasticsearch-model/spec/support/app.rb

Mongoid hasn't been released yet with support for Rails 6 so this PR adds a few `begin-rescue`'s to catch when Mongoid cannot be loaded.
When Mongoid is released with support for Rails 6, the changes in this PR can be removed.

Test Rails 6

---

elasticsearch-model/README.md

Sidekiq requires `perform` method for workers, with `perform_async` it doesn't work.

Small update README for asynchronous Callbacks

---

README.md

`gem install ...` is not Ruby, and the other places with `gem install` also use the indented block style.

[DOCS] Move `gem install` to a non-Ruby code block

---

elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb

Calling Model#import with Ruby 2.7 results in a deprecation warning due to passing options into `find_in_batches` as keyword arguments without explicitly stating so:
```
.../activerecord-6.0.3/lib/active_record/querying.rb:21: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
.../activerecord-6.0.3/lib/active_record/relation/batches.rb:126: warning: The called method `find_in_batches' is defined here
```

fix: Ruby 2.7 deprecation warning on find_in_batches

---

README.md
elasticsearch-rails/README.md
elasticsearch-rails/lib/rails/templates/01-basic.rb

Update README for generating app with template

---

elasticsearch-model/lib/elasticsearch/model.rb
elasticsearch-model/spec/elasticsearch/model/module_spec.rb

This PR reverts the line from this commit: https://github.com/elastic/elasticsearch-rails/pull/893/files to address the issue described here https://github.com/elastic/elasticsearch-rails/issues/924
My biggest concern is that this is a very subtle change in behavior that could lead to bugs, especially in a project where custom methods with similar names (import, search, etc.) are defined. It seems safer to keep the existing behavior (pre 7.x.x elasticsearch-rails) and force users who are facing this sort of conflict to be more explicit about their method choice (via `ModelName.__elasticsearch__.method()`)

[MODEL] Do not override existing methods

---

.github/stale.yml

Adds [Stale](https://github.com/apps/stale) - a GitHub Integration built with Probot that closes abandoned issues after a period of inactivity.

[CI] Adds stalebot configuration

---

elasticsearch-model/lib/elasticsearch/model/multimodel.rb

The simplest solution to deal with the [removal of types](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html) in ElasticSearch is simply to use single-type indices and not set `document_type` on models.
However Multimodel did not deal with that case and ended up calling a URL ending in `my-index//_search` instead of  `my-index/_search`, which caused the types warning:
> warning: 299 Elasticsearch-7.9.1-083627f112ba94dffc1232e8b42b73492789ef91 "[types removal] Specifying types in search requests is deprecated."
This PR fixes that issue.

deal with `nil` document types in Multimodel

---

elasticsearch-model/elasticsearch-model.gemspec

While creating a patch for #980, I have found out the currently supported
`elasticsearch` version by `elasticsearch-model` is unnecessarily wide. ( `> 1` )
Also, the previous dependency of `> 1` and the nonexistence of version-parameterized test
means that the CI is not running against versions under 7.x. for `elasticsearch-model`.
I doubt the current code on `master` still works for old versions,
and I would like to avoid writing code to support compatibility on old versions on master branch.
To solve this issue, I have updated the dependency based on Elasticsearch gems' version policy.
This improves gem consistency and maintenance efficiency.
c.f. 
https://github.com/elastic/elasticsearch-rails/tree/756a4dae1c51331a54bab8f00b0fcb88b4a480ad/elasticsearch-model#compatibility
#875

Update dependency to explicitly support version 7

---

elasticsearch-model/lib/elasticsearch/model/indexing.rb
elasticsearch-model/spec/elasticsearch/model/indexing_spec.rb

This fixes #980.
Passing `ignore: 404` to Elasticsearch::Client can stop
FATAL log in addition to stopping exception.
This option is supported since the 5.0.4 and 6.0.0 of `elasticsearch-ruby`.
https://github.com/elastic/elasticsearch-ruby/blob/36d45f0c12f4e9ef96646f269748ad33b43e974c/CHANGELOG.md#600
https://github.com/elastic/elasticsearch-ruby/blob/36d45f0c12f4e9ef96646f269748ad33b43e974c/CHANGELOG.md#504
This swallowing was implemented following exception catching as follows.
elastic/elasticsearch-ruby@9848c97
Unnecessary tests on exceptions are also removed, and following code
covers the required tests.
https://github.com/aeroastro/elasticsearch-rails/blob/c4daaad152517114aa568e326b0388ab8b883e1d/elasticsearch-model/spec/elasticsearch/model/indexing_spec.rb#L652-L661
I have confirmed …

Stop emitting FATAL log when checking existence of indices 

---

.github/workflows/2.4.yml
.github/workflows/2.5.yml
.github/workflows/2.6.yml
.github/workflows/2.7.yml
.github/workflows/jruby.yml
Gemfile
README.md
Rakefile
elasticsearch-model/elasticsearch-model.gemspec
elasticsearch-persistence/elasticsearch-persistence.gemspec
elasticsearch-rails/elasticsearch-rails.gemspec

This PR addresses some maintenance issues:
- Removes dev dependency on `elasticsearch-extensions`.
- Refactors GitHub Actions and updates the stack to use latest `7.x`.

Removes dependency on extensions, updates CI

---

.github/workflows/2.4.yml
.github/workflows/2.5.yml
.github/workflows/2.6.yml
.github/workflows/2.7.yml
.github/workflows/jruby.yml
.github/workflows/license.yml
elasticsearch-model/lib/elasticsearch/model.rb
elasticsearch-model/lib/elasticsearch/model/client.rb
elasticsearch-model/lib/elasticsearch/model/indexing.rb
elasticsearch-model/spec/elasticsearch/model/client_spec.rb
elasticsearch-model/spec/elasticsearch/model/indexing_spec.rb
elasticsearch-model/spec/elasticsearch/model/module_spec.rb
elasticsearch-persistence/spec/repository_spec.rb

Updates for using with client v7.14.0

---

elasticsearch-model/examples/activerecord_associations.rb
elasticsearch-model/examples/activerecord_custom_analyzer.rb
elasticsearch-model/lib/elasticsearch/model/response/results.rb
elasticsearch-model/spec/elasticsearch/model/response/results_spec.rb
elasticsearch-persistence/README.md
elasticsearch-persistence/examples/notes/test.rb

Updates transport references and alias for Elasticsearch::Model::Response::Results#records

---

elasticsearch-model/lib/elasticsearch/model/proxy.rb
elasticsearch-model/spec/elasticsearch/model/proxy_spec.rb

Since Ruby 3 changed the way keyword arguments work, Rails now only accepts keyword arguments for `find_in_batches`. Unfortunately, the `method_missing` implementation on `Elasticsearch::Model::Proxy` doesn't proxy keyword arguments, so Rails now explodes. The error is triggered by calling `Model.import`, and looks something like this:
```
ArgumentError: wrong number of arguments (given 1, expected 0)
bundle/gems/activerecord-6.1.3.1/lib/active_record/relation/batches.rb:128:in 'find_in_batches'
```
The fix is to forward not just positional arguments, but also keyword arguments. This PR adds a test (failing before the patch), and a patch to forward keyword arguments.
Fixes #989, #977.

Add compatibility with Ruby 3

---

README.md
elasticsearch-model/README.md
elasticsearch-rails/lib/rails/templates/04-dsl.rb

[DOCS] Updates README and links to elasticsearch-dsl

---

elasticsearch-rails/lib/elasticsearch/rails/tasks/import.rb

For tasks to work properly (i.e., find the models) the tasks need to have a dependency on the environment task (bootstraps the environment). Without this, the import tasks fail (e.g. `NameError: uninitialized constant User`).
Fixes https://github.com/elastic/elasticsearch-rails/issues/971 (and related issues)

Fix missing environment dependency for import tasks

---

README.md

When building an Elasticsearch environment in Docker according to the usage, the following error occurs when generating the sample rails application.
```
rails runner 'Article.__elasticsearch__.create_index! force: true' from "."
/Users/username/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/elasticsearch-7.17.7/lib/elasticsearch.rb:86:in `verify_with_version_or_header': The client noticed that the server is not a supported distribution of Elasticsearch. (Elasticsearch::UnsupportedProductError)
```
This is because the elasticsearch-ruby gem no longer supports oss only distributions.
https://github.com/elastic/elasticsearch-ruby/issues/1429
To avoid unnecessary errors, we suggest changing the name of the Docker Image for testing, which is introduced in Usage.
version control software: …

renamed docker image name in README

---

elasticsearch-model/README.md

Although https://github.com/elastic/elasticsearch-rails/tree/main/elasticsearch-model#compatibility says that `7.x` tag is not supported, `7.x` has been supported by https://github.com/elastic/elasticsearch-rails/commit/a0f14d96fab54b64cb3b8cbacd6476aba2dfa78d .
Then, I update README.
ref
* https://github.com/elastic/elasticsearch-rails/tree/main/elasticsearch-persistence#compatibility
* https://github.com/elastic/elasticsearch-rails/tree/main/elasticsearch-rails#compatibility

[MODEL] Update README. `7.x` is supported.

---

elasticsearch-model/elasticsearch-model.gemspec
elasticsearch-persistence/elasticsearch-persistence.gemspec
elasticsearch-rails/elasticsearch-rails.gemspec

This PR removes individual names and email addresses and replaces those with the new (external) [group email address](mailto:client-libs@elastic.co).

Updated project metadata to use group email address

---

elasticsearch-model/lib/elasticsearch/model/proxy.rb

https://github.com/elastic/elasticsearch-rails/blob/8fe0a555083d16d9d64dea7b0ae8a8695c1d4211/elasticsearch-model/lib/elasticsearch/model/proxy.rb#L118 defines an instance method.
But https://github.com/elastic/elasticsearch-rails/blob/8fe0a555083d16d9d64dea7b0ae8a8695c1d4211/elasticsearch-model/lib/elasticsearch/model/proxy.rb#L123 calls a class method.
So it should define as a singleton method of the module.

`ruby2_keywords` is not an instance method

---

elasticsearch-rails/lib/elasticsearch/rails/instrumentation/log_subscriber.rb
elasticsearch-rails/spec/instrumentation/log_subscriber_spec.rb
elasticsearch-rails/spec/spec_helper.rb

This PR switches the elasticsearch-rails gem to use a new signature of the ActiveSupport::LogSubscriber#color 
method when called in an app using Rails 7.1+. 
With older Rails, the gem uses the working, old signature.
An example of a deprecation warning visible in 7.1 apps 
```
DEPRECATION WARNING: Bolding log text with a positional boolean is deprecated and will be removed in Rails 7.2. Use an option hash instead (eg. `color("my text", :red, bold: true)`). (called from query_time_boundaries at timeseries/frequency_calculator.rb:44)
```

Address Rails 7.1 deprecation warning in elasticsearch-rails
